stages:
  - test
  - security
  - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  - component: gitlab.com/gitlab-components/code-quality/code-quality@main

test:
  stage: test
  image: php:8.3
  variables:
    XDEBUG_MODE: coverage
  before_script:
    - apt-get update && apt-get install -yq git unzip zip libzip-dev zlib1g-dev libexif-dev
    - docker-php-ext-install exif zip
    - pecl install xdebug && docker-php-ext-enable xdebug
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-scripts
    - cp config/config.sample.php config/config.php
  script:
    - vendor/bin/phpcs --standard=./phpcs.xml --parallel=8 src tests
    - php vendor/bin/phpunit --configuration phpunit.xml --exclude-group database  --coverage-text --coverage-cobertura=coverage.cobertura.xml
    - vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=512M
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml
  coverage: /^\s*Lines:\s*\d+.\d+\%/
  only:
    - merge_requests
    - master

deploy_to_github:
  stage: deploy
  script:
    - git checkout master
    - git push https://markbellingham:${GITHUB_TOKEN}@github.com/markbellingham/MyEspacio.git master:main
  only:
    - master
