stages:
  - test
  - security

# Security scanning job (SAST)
include:
  - template: Security/SAST.gitlab-ci.yml
  - component: gitlab.com/gitlab-components/code-quality/code-quality@main

# Job to run PHP CodeSniffer and PHPUnit
test:
  stage: test
  image: php:8.1
  variables:
    XDEBUG_MODE: coverage
  before_script:
    - apt-get update && apt-get install -yq git unzip zip libzip-dev zlib1g-dev libexif-dev
    - docker-php-ext-install exif zip
    - pecl install xdebug && docker-php-ext-enable xdebug
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-scripts
    - composer require --dev phpunit/phpunit phpunit/php-code-coverage phpstan/phpstan phpstan/phpstan-phpunit
    - cp config/config.sample.php config/config.php
  script:
    - vendor/bin/phpcs --standard=./phpcs.xml src tests
    - php vendor/bin/phpunit --configuration phpunit.xml --exclude-group database  --coverage-text --coverage-cobertura=coverage.cobertura.xml
    - vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=512M
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.cobertura.xml
  only:
    - merge_requests
    - master
