stages:
  - test
  - security

# Security scanning job (SAST)
include:
  - template: Security/SAST.gitlab-ci.yml
  - component: gitlab.com/gitlab-components/code-quality/code-quality@main

# Job to run PHP CodeSniffer and PHPUnit
test:
  stage: test
  image: php:8.1
  before_script:
    - apt-get update && apt-get install -y zip libexif-dev
    - docker-php-ext-install exif
    - pecl install xdebug
    - echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20210902/xdebug.so" >> /usr/local/etc/php/php.ini
    - echo "xdebug.mode=coverage" >> /usr/local/etc/php/php.ini
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-scripts
    - cp config/config.sample.php config/config.php
  script:
    - vendor/bin/phpcs --standard=./phpcs.xml src tests
    - vendor/bin/phpunit --configuration phpunit.xml --exclude-group database  --coverage-html coverage-report/ --colors=never
  artifacts:
    paths:
      - coverage-report/
  only:
    - merge_requests
    - master
