# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - security

# Security scanning job (SAST)
include:
  - template: Security/SAST.gitlab-ci.yml
  - component: gitlab.com/gitlab-components/code-quality/code-quality@main

# Job to run PHP CodeSniffer and PHPUnit
test:
  stage: test
  image: php:8.1
  before_script:
    - apt-get update && apt-get install -y zip libexif-dev
    - docker-php-ext-install exif
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-scripts
    - cp config/config.sample.php config/config.php
  script:
    - vendor/bin/phpcs --standard=./phpcs.xml src tests
    - vendor/bin/phpunit --configuration phpunit.xml
  only:
    - merge_requests
    - master
