<?php

declare(strict_types=1);

return [
    [
        'GET',
        '/',
        'Personly\FrontPage\Presentation\RootPageController#show'
    ],
    [
        'GET',
        '/home',
        'Personly\FrontPage\Presentation\FrontPageController#show'
    ],
    [
        'GET',
        '/music/{albumId: \d+}',
        'Personly\Music\Presentation\MusicController#getAlbumInfo'
    ],
    [
        'GET',
        '/music[/[{searchMusic:.+}]]',
        'Personly\Music\Presentation\MusicController#listMusic'
    ],
    [
        'GET',
        '/track/{trackId}',
        'Personly\Music\Presentation\MusicController#getTrackInfo'
    ],
    [
        'GET',
        '/photos[/[{searchPhotos:.+}]]',
        'Personly\Photos\Presentation\PhotosController#photoGrid'
    ],
    [
        'GET',
        '/photo/{id:\d+}',
        'Personly\Photos\Presentation\PhotosController#photoModal'
    ],
    [
        'GET',
        '/photo/{photoId:\d+}/comments',
        'Personly\Photos\Presentation\PhotosController#getComments'
    ],
    [
        'POST',
        '/photo/{id:\d+}/fave',
        'Personly\Photos\Presentation\PhotosController#addFave'
    ],
    [
        'POST',
        '/photo/{id:\d+}/comment',
        'Personly\Photos\Presentation\PhotosController#addComment'
    ],
    [
        'GET',
        '/lastfm',
        'Personly\Music\Presentation\LastFmController#show'
    ],
    [
        'GET',
        '/games[/[{selectedGame:[a-z]{6,}}]]',
        'Personly\Games\Presentation\GamesController#show',
    ],
    [
        'GET',
        '/contact',
        'Personly\Contact\Presentation\ContactController#show'
    ],
    [
        'POST',
        '/contact/send',
        'Personly\Contact\Presentation\ContactController#sendMessage'
    ],
    [
        'POST',
        '/login',
        'Personly\User\Presentation\LoginController#processLoginForm'
    ],
    [
        'GET',
        '/login/{magicLink: [a-zA-Z0-9]{40}}',
        'Personly\User\Presentation\LoginController#LoginWithMagicLink'
    ],
    [
        'POST',
        '/logout',
        'Personly\User\Presentation\LoginController#logout'
    ],
    [
        'GET',
        '/upload',
        'Personly\Photos\Presentation\UploadController#show'
    ],
    [
        'POST',
        '/upload',
        'Personly\Photos\Presentation\UploadController#upload'
    ],
    [
        'POST',
        '/photo/upload-photo-metadata',
        'Personly\Photos\Presentation\UploadController#savePhotoMetadata'
    ],
    [
        'POST',
        '/photo/upload-flickr-data',
        'Personly\Photos\Presentation\UploadController#uploadFlickrData'
    ]
];
