<?php

declare(strict_types=1);

return [
    [
        'GET',
        '/',
        'MyEspacio\Home\Presentation\RootPageController#show'
    ],
    [
        'GET',
        '/home',
        'MyEspacio\Home\Presentation\FrontPageController#show'
    ],
    [
        'GET',
        '/music/{albumId: \d+}',
        'MyEspacio\Music\Presentation\MusicController#getAlbumInfo'
    ],
    [
        'GET',
        '/music[/[{searchMusic:.+}]]',
        'MyEspacio\Music\Presentation\MusicController#listMusic'
    ],
    [
        'GET',
        '/track/{trackId}',
        'MyEspacio\Music\Presentation\MusicController#getTrackInfo'
    ],
    [
        'GET',
        '/photos[/[{searchPhotos:.+}]]',
        'MyEspacio\Photos\Presentation\PhotoController#photoGrid'
    ],
    [
        'GET',
        '/photo/{uuid:.+}',
        'MyEspacio\Photos\Presentation\PhotoController#singlePhoto'
    ],
    [
        'GET',
        '/photo/{uuid:.+}/comments',
        'MyEspacio\Photos\Presentation\PhotoController#getComments'
    ],
    [
        'POST',
        '/photo/{uuid:.+}/fave',
        'MyEspacio\Photos\Presentation\PhotoController#addFave'
    ],
    [
        'POST',
        '/photo/{uuid:.+}/comment',
        'MyEspacio\Photos\Presentation\PhotoController#addComment'
    ],
    [
        'GET',
        '/lastfm',
        'MyEspacio\Music\Presentation\LastFmController#show'
    ],
    [
        'GET',
        '/games[/[{selectedGame:[a-z]{6,}}]]',
        'MyEspacio\Games\Presentation\GamesController#show',
    ],
    [
        'GET',
        '/contact',
        'MyEspacio\Contact\Presentation\ContactController#show'
    ],
    [
        'POST',
        '/contact/send',
        'MyEspacio\Contact\Presentation\ContactController#sendMessage'
    ],
    [
        'POST',
        '/login',
        'MyEspacio\User\Presentation\LoginController#processLoginForm'
    ],
    [
        'GET',
        '/login/{magicLink: [a-zA-Z0-9]{40}}',
        'MyEspacio\User\Presentation\LoginController#LoginWithMagicLink'
    ],
    [
        'POST',
        '/logout',
        'MyEspacio\User\Presentation\LoginController#logout'
    ],
    [
        'GET',
        '/upload',
        'MyEspacio\Photos\Presentation\UploadController#show'
    ],
    [
        'POST',
        '/upload',
        'MyEspacio\Photos\Presentation\UploadController#upload'
    ],
    [
        'POST',
        '/photo/upload-photo-metadata',
        'MyEspacio\Photos\Presentation\UploadController#savePhotoMetadata'
    ],
    [
        'POST',
        '/photo/upload-flickr-data',
        'MyEspacio\Photos\Presentation\UploadController#uploadFlickrData'
    ]
];
