<?php

declare(strict_types=1);

return [
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]',
        'MyEspacio\FrontPage\Presentation\RootPageController#show'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]home',
        'MyEspacio\FrontPage\Presentation\FrontPageController#show'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]music/{albumId: \d+}',
        'MyEspacio\Music\Presentation\MusicController#getAlbumInfo'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]music[/[{searchMusic:.+}]]',
        'MyEspacio\Music\Presentation\MusicController#listMusic'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]track/{trackId}',
        'MyEspacio\Music\Presentation\MusicController#getTrackInfo'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]photos[/[{searchPhotos:.+}]]',
        'MyEspacio\Photos\Presentation\PhotosController#photoGrid'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]photo/{id:\d+}',
        'MyEspacio\Photos\Presentation\PhotosController#photoModal'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]photo/{photoId:\d+}/comments',
        'MyEspacio\Photos\Presentation\PhotosController#getComments'
    ],
    [
        'POST',
        '/[{language:[a-zA-Z]{2}}/]photo/{id:\d+}/fave',
        'MyEspacio\Photos\Presentation\PhotosController#addFave'
    ],
    [
        'POST',
        '/[{language:[a-zA-Z]{2}}/]photo/{id:\d+}/comment',
        'MyEspacio\Photos\Presentation\PhotosController#addComment'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]lastfm',
        'MyEspacio\Music\Presentation\LastFmController#show'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]games[/[{selectedGame:[a-z]{6,}}]]',
        'MyEspacio\Games\Presentation\GamesController#show',
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]contact',
        'MyEspacio\Contact\Presentation\ContactController#show'
    ],
    [
        'POST',
        '/[{language:[a-zA-Z]{2}}/]contact/send',
        'MyEspacio\Contact\Presentation\ContactController#sendMessage'
    ],
    [
        'POST',
        '/[{language:[a-zA-Z]{2}}/]login',
        'MyEspacio\User\Presentation\LoginController#processLoginForm'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]login/{magicLink: [a-zA-Z0-9]{40}}',
        'MyEspacio\User\Presentation\LoginController#LoginWithMagicLink'
    ],
    [
        'POST',
        '/[{language:[a-zA-Z]{2}}/]logout',
        'MyEspacio\User\Presentation\LoginController#logout'
    ],
    [
        'GET',
        '/[{language:[a-zA-Z]{2}}/]upload',
        'MyEspacio\Photos\Presentation\UploadController#show'
    ],
    [
        'POST',
        '/[{language:[a-zA-Z]{2}}/]upload',
        'MyEspacio\Photos\Presentation\UploadController#upload'
    ],
    [
        'POST',
        '/[{language:[a-zA-Z]{2}}/]photo/upload-photo-metadata',
        'MyEspacio\Photos\Presentation\UploadController#savePhotoMetadata'
    ],
    [
        'POST',
        '/[{language:[a-zA-Z]{2}}/]photo/upload-flickr-data',
        'MyEspacio\Photos\Presentation\UploadController#uploadFlickrData'
    ]
];
