CREATE DATABASE project;

USE project;

CREATE TABLE IF NOT EXISTS icons(
    icon_id INT(2) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    icon VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    colour VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS sections (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    visible TINYINT(1)
);

CREATE TABLE IF NOT EXISTS tags (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    tag VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE,
    uuid VARCHAR(40) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(255) UNIQUE,
    passcode_route VARCHAR(5),
    login_attempts INT NOT NULL DEFAULT 0,
    login_date DATETIME,
    magiC_link VARCHAR(255),
    phone_code VARCHAR(6)
);
