SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE pictures.photo_album;
TRUNCATE pictures.photo_comments;
TRUNCATE pictures.photo_faves;
TRUNCATE pictures.anon_photo_faves;
TRUNCATE pictures.photo_tags;
TRUNCATE pictures.albums;
TRUNCATE pictures.photos;
TRUNCATE pictures.geo;
TRUNCATE pictures.countries;
SET FOREIGN_KEY_CHECKS = 1;
